export const SELECT_LOCATION = 'SELECT_LOCATION';

export const LOCATIONS_LIST_LOADING = 'LOCATIONS_LIST_LOADING';
export const LOCATIONS_LIST_SUCCESS = 'LOCATIONS_LIST_SUCCESS';
export const LOCATIONS_LIST_ERROR = 'LOCATIONS_LIST_ERROR';

export const WEATHER_FORECAST_LOADING = 'WEATHER_FORECAST_LOADING';
export const WEATHER_FORECAST_SUCCESS = 'WEATHER_FORECAST_SUCCESS';
export const WEATHER_FORECAST_ERROR = 'WEATHER_FORECAST_ERROR';

export const SAVE_LOCATION = 'SAVE_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const RESTORE_SAVED_LOCATIONS = 'RESTORE_SAVED_LOCATIONS';
