export const SELECT_LOCATION = 'SELECT_LOCATION';

export const FETCH_LOCATIONS_LIST_LOADING = 'FETCH_LOCATIONS_LIST_LOADING';
export const FETCH_LOCATIONS_LIST_SUCCESS = 'FETCH_LOCATIONS_LIST_SUCCESS';
export const FETCH_LOCATIONS_LIST_ERROR = 'FETCH_LOCATIONS_LIST_ERROR';
