export const LOCATIONS_LIST_REQUEST = 'LOCATIONS_LIST_REQUEST';
export const LOCATIONS_LIST_SUCCESS = 'LOCATIONS_LIST_SUCCESS';
export const LOCATIONS_LIST_ERROR = 'LOCATIONS_LIST_ERROR';

export const WEATHER_FORECAST_REQUEST = 'WEATHER_FORECAST_REQUEST';
export const WEATHER_FORECAST_SUCCESS = 'WEATHER_FORECAST_SUCCESS';
export const WEATHER_FORECAST_ERROR = 'WEATHER_FORECAST_ERROR';

export const RESTORE_SAVED_LOCATIONS = 'RESTORE_SAVED_LOCATIONS';
export const TOGGLE_FAVORITE_LOCATIONS = 'TOGGLE_FAVORITE_LOCATIONS';

export const LOCATION_DETAILS_REQUEST = 'LOCATION_DETAILS_REQUEST';
export const LOCATION_DETAILS_SUCCESS = 'LOCATION_DETAILS_SUCCESS';
export const LOCATION_DETAILS_ERROR = 'LOCATION_DETAILS_ERROR';
